// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xanmwzeewtcfgcutusia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhbm13emVld3RjZmdjdXR1c2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTczMDIsImV4cCI6MjA2MDgzMzMwMn0.h4Kto8E50HGCrxapNIIC_xuJJPRBQwDYNXDs2CKzuVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);